sudo: required

services:
  - docker

cache:
  apt: true
  directories:
  - ${TRAVIS_BUILD_DIR}/gitian-docker/gitian-builder/cache
  - ${TRAVIS_BUILD_DIR}/gitian-docker/gitian-builder/inputs
before_install:
- echo "LAUNCHING at $(date)"
- cd ${TRAVIS_BUILD_DIR}
- echo "git clone https://github.com/guruvan/gitian-docker"
- test -d gitian-docker || mkdir -v gitian-docker
- cd gitian-docker
- git init
- git remote add origin https://github.com/guruvan/gitian-docker
- git fetch origin
- git checkout -t origin/master
- echo "GD_BUILD_URL=https://github.com/guruvan/maza" > maza.env
- echo "GD_BUILD_COMMIT=7e04017950b2b7d9377f54b402ca5b14b9a6d7cf" >> maza.env
- echo "GD_BUILD_COIN=maza" >> maza.env
- echo "GD_HOST_OSXSDK=${TRAVIS_BUILD_DIR}/gitian-docker/MacOSX10.9.sdk.tar.gz" >> maza.env
- echo "GD_BUILD_OSXSDK=MacOSX10.9.sdk.tar.gz" >> maza.env
- wget https://s3-us-west-2.amazonaws.com/downloads.maza.club/MacOSX10.9.sdk.tar.gz 
env:
- GD_OS_PACKAGE=linux
- GD_OS_PACKAGE=osx
- GD_OS_PACKAGE=win32
- GD_OS_PACKAGE=win64
install:
- echo "STARTING BUILD SCRIPT AT $(date)"
- cd ${TRAVIS_BUILD_DIR}
- cd gitian-docker
- docker pull maza/gitian-travis && docker tag -f maza/gitian-travis ${USER}/gitian-stage1
- ./build.sh maza.env all
- echo "FINISHED STAGE 1 at  $(date)"
script:
- cd ${TRAVIS_BUILD_DIR}/gitian-docker
- chmod +x ./linux-deps.sh ./osx-deps.sh ./win32-deps.sh ./win64-deps.sh ./win32.sh ./win64.sh ./linux.sh ./osx.sh
- ./${GD_OS_PACKAGE}-deps.sh
- ./${GD_OS_PACKAGE}.sh
- echo "You are done"

