sudo: required
dist: trusty
group: deprecated-2017Q3

os: linux
language: generic

services:
  - docker

before_install:
  - ls -la /bin/sh
  - ls -la /bin/dash
  - test -f /bin/dash || sudo apt-get install -y dash 
  


