sudo: required

services:
  - docker

before_install:
- docker pull mazaclub/encompass-release:0.6.0
- docker pull mazaclub/encompass-winbuild:0.6.0
- docker pull ogrisel/winbuilder
- cd ${TRAVIS_BUIL_DIR}
- git clone https://github.com/mazaclub/encompass
- git checkout release/v0.6.0
- cd encompass/contrib/mazaclub-release
- ./buildLinux 0.6.0 local

script:
- cd ${TRAVIS_BUILD_DIR}
- echo "Tanks" 
