sudo: required

services:
  - docker

before_install:
- cd ${TRAVIS_BUILD_DIR}
- git clone https://github.com/guruvan/gitian-docker
- cd gitian-docker
- echo "GD_BUILD_URL=https://github.com/mazacoin/mazacoin-new" > maza-10.2.env
- echo "GD_BUILD_COMMIT=10.2" >> maza-10.2.env
- echo "GD_BUILD_COIN=maza" >> maza-10.2.env
- echo "GD_HOST_OSXSDK=${TRAVIS_BUILD_DIR}/gitian-docker/MacOSX10.9.sdk.tar.gz" >> maza-10.2.env
- echo "GD_BUILD_OSXSDK=MacOSX10.9.sdk.tar.gz" >> maza-10.2.env
- wget https://s3-us-west-2.amazonaws.com/downloads.maza.club/MacOSX10.9.sdk.tar.gz 
- ./build.sh maza-10.2.env

script:
- cd ${TRAVIS_BUILD_DIR}
- echo "Tanks" 
