sudo: required

services:
  - docker

before_install:
- cd ${TRAVIS_BUIL_DIR}
- git clone https://github.com/guruvan/gitian-docker
- cd gitian-docker
- touch MacOSXSDK.tar.gz
- sed 's/\/Users\/guruvan\/DEVEL\/OSX_SDK\///g' maza-10.2.env > maza.env
- ./build.sh maza.env

script:
- cd ${TRAVIS_BUILD_DIR}
- echo "Tanks" 
